### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by ronghui19** [open-mmlab/mmgeneration#4]
**Describe the bug**
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Reproduction**

1. What command or script did you run?

```
  from mmgen.apis import init_model, sample_uncoditional_model
  
  config_file = 'configs/styleganv2/stylegan2_c2_lsun-church_256_b4x8_800k.py'
  # you can download this checkpoint in advance and use a local file path.
  checkpoint_file = 'http://download.openmmlab.com/mmgen/stylegan2/official_weights/stylegan2-church-config-f-official_20210327_172657-1d42b7d1.pth'
  device = 'cuda:0'
  # init a generatvie
  model = init_model(config_file, checkpoint_file, device=device)
  # sample images
  fake_imgs = sample_uncoditional_model(model, 4)
```

**Environment**
sys.platform: linux
Python: 3.8.3 (default, May 19 2020, 18:47:26) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1+cu111
OpenCV: 4.5.1
MMCV: 1.3.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.11.0+2313bd7

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    fake_imgs = sample_uncoditional_model(model, 4)
  File "/home/zhanronghui/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhanronghui/mmlab/mmgeneration/mmgen/apis/inference.py", line 78, in sample_uncoditional_model
    res = model.sample_from_noise(
  File "/home/zhanronghui/mmlab/mmgeneration/mmgen/models/gans/base_gan.py", line 166, in sample_from_noise
    outputs = _model(noise, num_batches=num_batches, **kwargs)
  File "/home/zhanronghui/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhanronghui/mmlab/mmgeneration/mmgen/models/architectures/stylegan/generator_discriminator_v2.py", line 340, in forward
    styles = [self.style_mapping(s) for s in styles]
  File "/home/zhanronghui/mmlab/mmgeneration/mmgen/models/architectures/stylegan/generator_discriminator_v2.py", line 340, in <listcomp>
    styles = [self.style_mapping(s) for s in styles]
  File "/home/zhanronghui/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhanronghui/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/zhanronghui/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhanronghui/mmlab/mmgeneration/mmgen/models/architectures/stylegan/modules/styleganv2_modules.py", line 86, in forward
    x = self.linear(x)
  File "/home/zhanronghui/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 875, in _call_impl
    result = hook(self, input)
  File "/home/zhanronghui/mmlab/mmgeneration/mmgen/models/architectures/pggan/modules.py", line 67, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "/home/zhanronghui/mmlab/mmgeneration/mmgen/models/architectures/pggan/modules.py", line 59, in compute_weight
    weight = weight * torch.tensor(
RuntimeError: CUDA error: no kernel image is available for execution on the device

```

**Comment by nbei** [comment]
Hi @ronghui19 , it is wired that the error is reported at the first step, which is a very simple operation. Could you run the following command on your environment and provide more information?

```shell
>>> import torch
>>> a = torch.randn(2, 4).cuda()
>>> b = a * torch.tensor(1., dtype=torch.float32)
```

**Comment by ronghui19** [comment]
@nbei 

it works fine and there is no error.

**Comment by nbei** [comment]
Ok, I will close this issue.

**Comment by nbei** [comment]
Sorry for misunderstanding your words. I just reopen it.

**Comment by nbei** [comment]
Could you try it on other devices? One way to try is:
```python
model = init_model(config_file, checkpoint_file, device=device).cpu()
```
Firstly, we can try it on CPU device and see what will happen.

**Comment by LeoXing1996** [comment]
> @nbei
> 
> it works fine and there is no error. I dont know what'g going on.

Switch your PyTorch version to 1.8.0 and reinstall `mmcv-full` may solve this problem.

**Comment by nbei** [comment]
Closed for no response. We will reopen it if receiving any further questions.

**Comment by ronghui19** [comment]
everything works fine now

**Comment by daiyuanm** [comment]
> everything works fine now

I also encountered the same problem, how did you solve it?

**Comment by ronghui19** [comment]
> > everything works fine now
> 
> I also encountered the same problem, how did you solve it?

i reinstalled mmcv

**Comment by daiyuanm** [comment]
> > > everything works fine now
> > 
> > 
> > I also encountered the same problem, how did you solve it?
> 
> i reinstalled mmcv

I have reinstalled it several times and still have this problem. :disappointed_relieved:

**Comment by wangruohui** [comment]
#52
